-- Create a specific table for daily meal selections
create table user_meals (
  id bigint generated by default as identity primary key,
  user_email text not null,
  meal_date text not null, -- Format: YYYY-MM-DD
  meal_type text not null, -- 'veg' or 'meat'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_email, meal_date) -- Ensure one meal per user per day
);

alter table user_meals enable row level security;

create policy "Enable access for own meals" on "public"."user_meals"
as permissive for all
to public
using (true)
with check (true);
