-- Run this in your Supabase SQL Editor

-- Create the orders table
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  items jsonb,
  total_amount numeric,
  status text
);

-- Turn on Row Level Security (RLS) is recommended but for now we will allow public insert for demo
alter table orders enable row level security;

-- Create a policy that allows anyone to insert orders (for the demo app)
create policy "Enable insert for all users" on "public"."orders"
as permissive for insert
to public
with check (true);

-- (Optional) Create a policy to allow reading orders if you want to see them in a dashboard app later
create policy "Enable read access for all users" on "public"."orders"
as permissive for select
to public
using (true);
